### ISSUE TITLE
Support node.js environments

### ISSUE THREAD

**Issue by danvk** [algolia/faux-jax#1]
From a Mocha test:

```javascript
var fauxJax = require('faux-jax');
```

produces:

```
Running "mochaTest:test" (mochaTest) task
>> Mocha exploded!
>> ReferenceError: document is not defined
>>     at Object.<anonymous> (/Users/danvk/github/pileup.js/node_modules/faux-jax/lib/ie.js:17:20)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
>>     at Module.require (module.js:364:17)
>>     at require (module.js:380:17)
>>     at Object.<anonymous> (/Users/danvk/github/pileup.js/node_modules/faux-jax/index.js:51:1)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
```

i.e. it looks like node.js is being detected as Internet Explorer.

**Comment by vvo** [comment]
Faux-jax only support AJAX requests, as for mocking node.js request I would suggest either http://sinonjs.org/docs/#fakeServer or https://github.com/pgte/nock

If you ask me, you better well differenciate mocking node.js requests from browser requests.

Of course you can have only one module handling both, but there's too much magic involved.

Right now faux-jax support browsers (and browserify so), I do not know if I'll add Node.js support.

**Comment by danvk** [comment]
Sinon's fakeServer is known to not work under node.js. Supporting node is a goal for Sinon 2.0: https://github.com/cjohansen/Sinon.JS/issues/319

nock seems to be a fake for Node's `http` module, not `XMLHttpRequest`.

It's fine for this to be out-of-scope for faux-jax, but I don't think those are viable alternatives :)

**Comment by vvo** [comment]
@danvk But there's no XMLHttpRequest object in node.js, why would you want to mock it?

**Comment by vvo** [comment]
In Node.JS environment, every request goes through the http module, so using nock should be enough.

Maybe you ar etrying to do something I do not understand right now, please tell me more

**Comment by danvk** [comment]
I see. Context: I'm running tests with `mocha`, which is often used to test browser code in a node environment.

**Comment by vvo** [comment]
If you want to run browser test, you better make them run in a browser. I know it sound obvious but still, running browser test in a Node.JS environment only leads to problems at some point.

If you want to write moch tests and have them run in a real browser, see [zuul](https://github.com/defunctzombie/zuul) or [testem](https://github.com/airportyh/testem) or even [karma](http://karma-runner.github.io/0.12/index.html).

faux-jax is [fully tested](https://github.com/algolia/faux-jax/tree/master/test) and tests are run in real browsers, https://github.com/algolia/faux-jax/blob/master/package.json#L8

Let me know

**Comment by vvo** [comment]
@danvk `faux-jax` now supports Node.js environments. It will intercept http(s) module.

**Comment by danvk** [comment]
Cool. BTW, I've very much taken your advice to heart:

> If you want to run browser test, you better make them run in a browser.

Words of wisdom! It does sound obvious, but testing browser code turns out to be way easier in a browser. :)
