### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by srph** [algolia/faux-jax#11]
I get this error `{ [Error: socket hang up] code: 'ECONNRESET' }`, as I ran `faux-jax`.

Here's my code:
```js
var expect = require('chai').expect;
var faux = require('faux-jax');
var axios = require('axios');

describe('axios-base-url interceptor', function() {
  it('should not append the base-url if request url is absolute', function(done) {
    faux.install();
    axios.get('http://swag.com/hehe').then(done, done);

    faux.on('request', function(request) {
      request.respond(200, { 'Content-Type': 'text/plain' }, '');
      faux.restore();
    });
  });
});
```

I'm not sure if this is related to axios as it simply uses `http` when in node under the hood.

## Demo
Check out this [repo](https://github.com/chirigarikku/faux-jax-econnreset-bug)

**Comment by vvo** [comment]
Thanks for the bug report, should be better now, let me now (upgrade to v4.2.2)
