### ISSUE TITLE
Recently upgraded to Node 6.9.1 from Node 4.6 and all faux-jax tests are broken.

### ISSUE THREAD

**Issue by djbobbydrake** [algolia/faux-jax#24]
I recently upgraded to node 6.9.1 and all my faux-jax tests are breaking. For one test, I saw this error message: `TypeError: normalizeConnectArgs is not a function` from `node_modules/mitm-algolia/index.js`. Any ideas?

**Comment by djbobbydrake** [comment]
Nevermind. It looks like I was on 7.0.0. Switched to 6.9.1 and things are fine.

**Comment by vvo** [comment]
Nice
