### ISSUE TITLE
faux network error

### ISSUE THREAD

**Issue by terinjokes** [algolia/faux-jax#5]
There doesn't seem to be a way to fake a network error, and trigger the second step of https://xhr.spec.whatwg.org/#handle-errors.

The closest we have is `xhr.abort()`, which sets the response to a NetworkError error, and follows the "end-user abort" steps. Notably, it does not trigger the "error" event.

Would you be interested in a pull request for this functionality?

---

In libraries, this is resolvable by handling the "readystatechange" event instead of "load" and "error", but I still believe it's a bug that this code path is not triggerable.

**Comment by vvo** [comment]
I am interested in all PR of course.

Can you detail a little bit the changes you want to add? Do you only want to enhance the abort() steps?

**Comment by terinjokes** [comment]
I was thinking a different method, `xhr.abort()`'s behavior is currently correct.

**Comment by vvo** [comment]
So you want to create a non-spec method that will trigger a network-error on the XHR?

Seems legit for testing purposes, go on

**Comment by terinjokes** [comment]
> Seems legit for testing purposes, go on

If it wasn't, we'd have a minor problem around `setResponseHeaders` and `setResponseBody` too. :wink:

**Comment by vvo** [comment]
what?

**Comment by vvo** [comment]
Oh you mean setResponseHeaders and setResponesBody are non-spec methods? Also respond :)

**Comment by vvo** [comment]
I could have go:

```js
fauxJax.respond(xhr, ..)
```

it would have worked but I guess some non-spec methods are a good tradeoff.

**Comment by vvo** [comment]
@terinjokes In my tests, I use `.onerror()` on the xhr object.

**Comment by terinjokes** [comment]
@vvo In my tests, calling `xhr.abort()` did not trigger the "error" event, only the "abort" event.

**Comment by vvo** [comment]
ok so we close this?

**Comment by terinjokes** [comment]
No. I have no way to trigger the "error" event to simulate a network error.

**Comment by vvo** [comment]
I am sorry I thought ypu could just trigger it by hand: xhr.onerror() will trigger any handler attached to onerror. hacky but works

**Comment by terinjokes** [comment]
Aye, unless your error handling code expects things like "status" and "statusText" to be in certain states. (Not saying mine does, but you know someone's does)

**Comment by vvo** [comment]
You could also set status and statusText to some values then emit error event. Again hacky but any error wrapper will do this in the end?

**Comment by terinjokes** [comment]
@vvo if we wrap it up into a non-standard method, that was satisfy me, or at the very least some documentation about it. Not a *huge* priority for me, mostly opened the ticket to raise awareness.
